include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    # prefer_const_constructors: true
    public_member_api_docs: false
    sort_pub_dependencies: true