name: ubuntu_welcome
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.20
  yaru: ^0.2.1
  yaru_widgets: ^1.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  ubuntu_localizations:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_localizations
      

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/